# Generated by Django 4.0.1 on 2022-01-05 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieces',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='knightaudits',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 14, 34, 48, 729128)),
        ),
    ]
