# Generated by Django 4.0.1 on 2022-01-05 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight', '0002_pieces_color_alter_knightaudits_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='knightaudits',
            name='possibilities',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='knightaudits',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 16, 38, 43, 159863)),
        ),
    ]
