# Generated by Django 4.0.1 on 2022-01-06 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight', '0003_knightaudits_possibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knightaudits',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 21, 20, 23, 893804)),
        ),
    ]
