# Generated by Django 4.0.1 on 2022-01-06 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight', '0004_alter_knightaudits_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knightaudits',
            old_name='posisiton',
            new_name='positon',
        ),
        migrations.AlterField(
            model_name='knightaudits',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 21, 26, 58, 654487)),
        ),
    ]
