# Generated by Django 4.0.1 on 2022-01-06 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knight', '0005_rename_posisiton_knightaudits_positon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knightaudits',
            old_name='positon',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='knightaudits',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 21, 46, 2, 18271)),
        ),
    ]
